# file: .github/workflows/hello-world.yml
name: NodeJS CI
# on – определяет события, которые запускают воркфлоу
on: push
jobs:
  # build – произвольно выбранное имя задания
  # их может быть больше одного
  build:
    # операционная система для работы воркфлоу
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Setup Node 18.x
        uses: actions/setup-node@v3
        with:
          bode-version: 18.x
          cache: npm
      - run: npm install
      - run: npm run build
      - run: npm test
      - run: npx eslint .
